name: conditionals
on: [push,create]
jobs:
  printPush:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps: 
      - name: print_event_name
        run: echo "this is push event"
  printCreate:
     if: github.event_name == 'create'
     runs-on: ubuntu-latest
     steps: 
      - name: print_event_name
        run: echo "Did you create a branch or a tag ?"
